import './AllumerLed.js';
import './AttendreS.js';
import './AttendreMs.js';
import './BouttonPresse/BoutonPresse.js';
import './EteindreLed.js';
import './LedImage.js';
import './Penche/Penche.js';
import './PourToujours.js';
import './ScrollText.js';
